SI_API_KEY: Test
aircraft_request_interval: 2
ground_check_interval: 1
logging_datefmt: '%H:%M:%S'
logging_format: '%(asctime)s - %(levelname)s - %(message)s'
logging_level: DEBUG
max_menu_check_attempts: 15
menu_file_paths:
- C:\Program Files (x86)\Addon Manager\MSFS\fsdreamteam-gsx-pro\html_ui\InGamePanels\FSDT_GSX_Panel\menu
- C:\Program Files\Addon Manager\MSFS\fsdreamteam-gsx-pro\html_ui\InGamePanels\FSDT_GSX_Panel\menu
sleep_long: 0.1
sleep_short: 0.1
position_keywords:
  gsx_gate:
  - Gate
  - Dock
  gsx_parking:
  - Parking
  - Stand
  - Remote
  - Ramp
  - Apron
  si_terminal:
  - Terminal
  - International
  - Parking
  - Domestic
  - Main
  - Central
  - Pier
  - Concourse
  - Level
  - Apron
  - Stand
